# 日志级别(低到高：DEBUG-INFO-WARN-ERROR)
log_level: INFO

# 是否将日志打印到控制台
print_console_flag: False

# 单个日志文件限制大小(兆)
log_file_limit_size: 10

# 日志文件备份数
log_file_backup_count: 5

# 日志保留时间(日)
local_business_logs_retain_time: 30

# 值域匹配日志路径
#range_match_local_business_logs_path: /mnt/sdb/qn_business_logs
range_match_local_business_logs_path: D:/GitRepository/IntelligentSupportPlatform/range_matching/logs

# 数据库地址
db:
  es:
    host: 10.101.37.162
    port: 9200
    batch_num: 5000

# 索引信息
index:
  range_matching:
    index_name: range
    doc_type: hospital_standard

